name: "MAMIE'S - Best Crepes in London"
favicon: null
layout_spectrum: 0.9319193030241877
typography_spectrum: 0.147632708074525
title: ' Best Crepes in London'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8806299213320017
  lightness: 0.5233415239490569
  saturation: 0.0672108440194279
  rhythmicContrast: 0.08616790478117764
purpose: []
