name: "MAMIE'S"
favicon: null
layout_spectrum: 0.90967
typography_spectrum: 0.08078
title: ' Best Crepes in London'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ffffff'
    - '#b0afaf'
    - '#5ca2c6'
    - '#5c595a'
  brandStrength: 0.8806299213320017
  lightness: 0.5233415239490569
  saturation: 0.0672108440194279
  rhythmicContrast: 0.08616790478117764
purpose: []
